complete -c bashref -f
complete -c bashref -n '__fish_use_subcommand' -a 'search'
complete -c bashref -n '__fish_use_subcommand' -a 'show'
complete -c bashref -n '__fish_use_subcommand' -a 'builtin'
complete -c bashref -n '__fish_use_subcommand' -a 'syntax'
complete -c bashref -n '__fish_use_subcommand' -a 'expansion'
complete -c bashref -n '__fish_use_subcommand' -a 'option'
complete -c bashref -n '__fish_use_subcommand' -a 'shopt'
complete -c bashref -n '__fish_use_subcommand' -a 'variable'
complete -c bashref -n '__fish_use_subcommand' -a 'example'
complete -c bashref -n '__fish_use_subcommand' -a 'list'
complete -c bashref -n '__fish_use_subcommand' -a 'lang'
complete -c bashref -n '__fish_use_subcommand' -a 'man'
complete -c bashref -n '__fish_use_subcommand' -a 'docs'
complete -c bashref -n '__fish_use_subcommand' -a 'completion'
complete -c bashref -n '__fish_use_subcommand' -a 'usage'
complete -c bashref -n '__fish_use_subcommand' -a 'doctor'
